"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar" | "fr";

export const translations = {
    en: {
        // Greeting
        greeting_morning: "Good morning",
        greeting_afternoon: "Good afternoon",
        greeting_evening: "Good evening",
        // Landing
        sign_in: "Sign in",
        get_started: "Get started free",
        hero_badge: "Study. Earn XP. Level Up. Repeat.",
        hero_title_1: "Study Smarter.",
        hero_title_2: "Level Up.",
        hero_desc: "The only productivity platform that makes studying addictive. Pomodoro sessions, AI quizzes, real-time leaderboards, and a friends system built for students.",
        hero_cta: "Start for free",
        hero_students: "students already leveling up",
        stat_pass: "Pass rate improvement",
        stat_daily: "Average daily study",
        stat_quizzes: "AI quizzes generated",
        stat_sessions: "Study sessions completed",
        features_label: "Everything you need",
        features_title: "Built for serious students",
        features_desc: "Every feature designed to keep you motivated, organized, and making progress.",
        feat_pomodoro_title: "Pomodoro Timer",
        feat_pomodoro_desc: "Focus in deep work sprints. Track every session and earn XP as you study.",
        feat_quiz_title: "AI Quiz Generator",
        feat_quiz_desc: "Upload any PDF and get an instant personalized quiz. Study smarter with AI.",
        feat_gamify_title: "Gamification",
        feat_gamify_desc: "Earn XP, level up, unlock badges, and maintain study streaks.",
        feat_social_title: "Social Study",
        feat_social_desc: "Add friends, compete on leaderboards, and hold each other accountable.",
        feat_tasks_title: "Smart Tasks",
        feat_tasks_desc: "Organize tasks by subject, priority, and deadline. Never miss a thing.",
        feat_calendar_title: "Study Calendar",
        feat_calendar_desc: "Plan sessions, track exams, and visualize your entire study schedule.",
        cta_streak: "Start your streak today",
        cta_title: "Ready to level up your studies?",
        cta_desc: "Join thousands of students who have transformed how they study. Free forever. No credit card required.",
        cta_button: "Create free account",
        cta_xp: "🎁 Get +100 XP just for signing up",
        footer_copy: "© 2025 Nahda.Edu. Built for students, by students.",
        footer_credit: "Designed & built by",
        footer_tagline: "a student, for students 🎓",
        // Sidebar
        nav_dashboard: "Dashboard",
        nav_pomodoro: "Pomodoro",
        nav_tasks: "Tasks",
        nav_calendar: "Calendar",
        nav_quiz: "AI Quiz",
        nav_achievements: "Achievements",
        nav_leaderboard: "Leaderboard",
        nav_friends: "Friends",
        nav_showcase: "Showcase",
        nav_profile: "Profile",
        nav_signout: "Sign out",
        sidebar_tagline: "Level up your studies",
        sidebar_xp_to_level: "XP to level",
        sidebar_day_streak: "day streak",
        clock_close: "Click anywhere to close · Press Esc",
        // Dashboard
        stat_studied_today: "Studied Today",
        stat_this_week: "this week",
        stat_pomodoros: "Pomodoros",
        stat_sessions_today: "sessions today",
        stat_tasks_done: "Tasks Done",
        stat_remaining: "remaining",
        stat_study_streak: "Study Streak",
        stat_best: "Best",
        stat_days: "days",
        dash_weekly_study: "Weekly Study Time",
        dash_total: "total",
        dash_todays_tasks: "Today's Tasks",
        dash_view_all: "View all",
        dash_all_done: "All caught up! Add some tasks.",
        dash_due: "Due",
        dash_manage_tasks: "Manage all tasks",
        dash_your_progress: "Your Progress",
        dash_level: "Level",
        dash_xp_needed: "XP needed",
        dash_to_level: "to Level",
        dash_total_xp: "Total XP",
        dash_studied: "Studied",
        dash_quick_start: "Quick Start",
        dash_start_pomodoro: "Start Pomodoro",
        dash_focus_session: "Focus session",
        dash_add_task: "Add Task",
        dash_track_work: "Track your work",
        dash_generate_quiz: "Generate Quiz",
        dash_from_pdf: "From your PDF",
        dash_recent_badges: "Recent Badges",
        dash_top_subjects: "Top Subjects",
        dash_study_time: "Study time",
        // Pomodoro
        pom_title: "Pomodoro Timer",
        pom_subtitle: "Deep work in focused intervals",
        pom_settings: "Settings",
        pom_focus: "Focus",
        pom_short_break: "Short Break",
        pom_long_break: "Long Break",
        pom_focus_time: "Focus Time",
        pom_break_time: "Short Break",
        pom_long_break_time: "Long Break",
        pom_session: "Session #",
        pom_no_subject: "No subject",
        pom_working_on: "What are you working on?",
        pom_todays_progress: "Today's Progress",
        pom_sessions: "Sessions",
        pom_focused: "Focused",
        pom_xp_earned: "XP Earned",
        pom_all_time: "All-time",
        pom_recent_sessions: "Recent Sessions",
        pom_no_sessions: "No sessions yet. Start your first focus session!",
        pom_focus_session_label: "Focus session",
        pom_pro_tip: "Pro Tip",
        pom_tip_text: "Skipping logs only the time you actually studied — every minute counts!",
        pom_settings_title: "Timer Settings",
        pom_focus_duration: "Focus Duration",
        pom_short_break_dur: "Short Break",
        pom_long_break_dur: "Long Break",
        pom_sessions_long: "Sessions → Long Break",
        pom_auto_breaks: "Auto-start breaks",
        pom_auto_focus: "Auto-start focus",
        pom_changes_note: "Changes take effect after applying",
        pom_cancel: "Cancel",
        pom_apply: "Apply",
        pom_session_label: "session",
        pom_sessions_label: "sessions",
        pom_min: "min",
        // Todos
        todos_title: "Tasks",
        todos_add: "Add Task",
        todos_completed: "completed",
        todos_remaining: "remaining",
        todos_total: "Total",
        todos_done: "Done",
        todos_pending: "Pending",
        todos_urgent: "Urgent",
        todos_new_task: "New Task",
        todos_task_title: "Task title",
        todos_description: "Description (optional)",
        todos_priority: "Priority",
        todos_subject: "Subject",
        todos_due_date: "Due Date",
        todos_none: "None",
        todos_cancel: "Cancel",
        todos_add_btn: "Add Task",
        todos_filter_all: "all",
        todos_filter_pending: "pending",
        todos_filter_completed: "completed",
        todos_no_tasks: "No tasks here",
        todos_add_first: "Add your first task to get started!",
        todos_no_filter: "No tasks.",
        todos_overdue: "(overdue)",
        // Friends
        friends_title: "Friends",
        friends_subtitle: "Study together, grow together",
        friends_find: "Find Students",
        friends_search_ph: "Search by username or name...",
        friends_search_btn: "Search",
        friends_already: "Friends",
        friends_requested: "Requested",
        friends_add: "Add",
        friends_requests: "Friend Requests",
        friends_accept: "Accept",
        friends_your_friends: "Your Friends",
        friends_no_friends: "No friends yet",
        friends_no_friends_sub: "Search for students above to add them",
        friends_xp: "XP",
        friends_streak: "Streak",
        friends_studied: "Studied",
        // Leaderboard
        lb_title: "Leaderboard",
        lb_subtitle: "Compete with fellow students. Rise to the top!",
        lb_xp: "⚡ XP",
        lb_streak: "🔥 Streak",
        lb_study_time: "⏱ Study Time",
        lb_you: "You",
        lb_days: "days",
        lb_studied: "studied",
        lb_level: "Level",
        // Quiz
        quiz_title: "AI Quiz Generator",
        quiz_subtitle: "Upload a PDF and get an instant personalized quiz",
        quiz_drop: "Drop your PDF here",
        quiz_drop_sub: "or click to browse · max 10MB",
        quiz_remove: "Remove",
        quiz_quiz_title: "Quiz Title",
        quiz_title_hint: "(optional — AI will suggest one)",
        quiz_title_ph: "e.g. Chapter 3: Cell Biology",
        quiz_difficulty: "Difficulty",
        quiz_easy: "Easy",
        quiz_medium: "Medium",
        quiz_hard: "Hard",
        quiz_mixed: "Mixed",
        quiz_num_questions: "Number of Questions",
        quiz_generate: "Generate Quiz",
        quiz_analyzing: "Analyzing your document...",
        quiz_extracting: "Extracting key concepts...",
        quiz_crafting: "Crafting smart questions...",
        quiz_adding: "Adding hints and explanations...",
        quiz_almost: "Almost ready...",
        quiz_wait: "This usually takes 10–20 seconds",
        quiz_question: "Question",
        quiz_of: "of",
        quiz_explanation: "Explanation",
        quiz_get_ai: "Get AI explanation",
        quiz_getting_ai: "Getting AI feedback...",
        quiz_ai_tutor: "AI Tutor",
        quiz_correct: "Correct! +XP",
        quiz_incorrect: "Incorrect",
        quiz_see_results: "See Results",
        quiz_next: "Next Question",
        quiz_xp_earned: "XP earned",
        quiz_new_quiz: "New Quiz",
        quiz_retry: "Retry",
        quiz_correct_label: "correct",
        // Profile
        profile_edit: "Edit Profile",
        profile_save: "Save",
        profile_cancel: "Cancel",
        profile_bio_ph: "Your bio...",
        profile_full_name_ph: "Full name",
        profile_level: "Level",
        profile_streak: "Streak",
        profile_total_xp: "Total XP",
        profile_member_since: "Member since",
        profile_days: "days",
        profile_pts: "pts",
        profile_current_level: "Current Level",
        profile_xp_week: "XP Earned This Week",
        profile_showcase: "Work Showcase",
        profile_achievements: "Recent Achievements",
        profile_app_dev: "App Developer",
        profile_earned: "Earned",
        // Showcase
        showcase_title: "Work Showcase",
        showcase_subtitle: "Share your academic work — papers, projects, and research",
        showcase_add: "Add Work",
        showcase_form_title: "Add to Showcase",
        showcase_title_ph: "Title (e.g. Research on Climate Change Impact)",
        showcase_type: "Type",
        showcase_subject: "Subject / Course",
        showcase_subject_ph: "e.g. Biology, CS101",
        showcase_desc: "Description",
        showcase_desc_ph: "Brief description of your work...",
        showcase_link: "External Link (optional)",
        showcase_link_ph: "https://docs.google.com/...",
        showcase_pdf: "Upload PDF (optional, max 20 MB)",
        showcase_pdf_click: "Click to upload a PDF",
        showcase_public: "Public — visible on your profile",
        showcase_private: "Private — only you can see this",
        showcase_cancel: "Cancel",
        showcase_submit: "Add to Showcase",
        showcase_uploading: "Uploading PDF…",
        showcase_saving: "Saving…",
        showcase_no_works: "No works yet",
        showcase_no_works_sub: "Share your academic work — papers, research, projects — and let it appear on your public profile.",
        showcase_add_first: "Add your first work",
        showcase_public_label: "Public",
        showcase_private_label: "Private",
        showcase_view_link: "View Link",
        showcase_view_pdf: "View PDF",
        showcase_hide_pdf: "Hide PDF",
        showcase_open_tab: "Open in new tab",
    },

    ar: {
        greeting_morning: "صباح الخير",
        greeting_afternoon: "مساء الخير",
        greeting_evening: "مساء الخير",
        sign_in: "تسجيل الدخول",
        get_started: "ابدأ مجاناً",
        hero_badge: "ادرس. اكسب XP. ارتقِ. كرر.",
        hero_title_1: "ادرس بذكاء.",
        hero_title_2: "ارتقِ بمستواك.",
        hero_desc: "المنصة الوحيدة للإنتاجية التي تجعل الدراسة مسلية.",
        hero_cta: "ابدأ مجاناً",
        hero_students: "طالب يرتقون بمستواهم الآن",
        stat_pass: "تحسن نسبة النجاح",
        stat_daily: "متوسط الدراسة اليومية",
        stat_quizzes: "اختبار بالذكاء الاصطناعي",
        stat_sessions: "جلسة دراسية مكتملة",
        features_label: "كل ما تحتاجه",
        features_title: "مصمم للطلاب الجادين",
        features_desc: "كل ميزة مصممة لإبقائك متحفزاً ومنظماً وتحقيق التقدم.",
        feat_pomodoro_title: "مؤقت بومودورو",
        feat_pomodoro_desc: "ركز في جلسات عمل مكثفة. تتبع كل جلسة واكسب XP.",
        feat_quiz_title: "منشئ الاختبارات بالذكاء الاصطناعي",
        feat_quiz_desc: "ارفع أي ملف PDF واحصل على اختبار شخصي فوري.",
        feat_gamify_title: "نظام المكافآت",
        feat_gamify_desc: "اكسب XP، ارتقِ بمستواك، افتح الشارات، وحافظ على سلاسل الدراسة.",
        feat_social_title: "الدراسة الاجتماعية",
        feat_social_desc: "أضف أصدقاء، تنافس على المتصدرين، وتحفزوا معاً.",
        feat_tasks_title: "المهام الذكية",
        feat_tasks_desc: "نظم المهام حسب المادة والأولوية والموعد النهائي.",
        feat_calendar_title: "تقويم الدراسة",
        feat_calendar_desc: "خطط للجلسات، تتبع الامتحانات، وصوّر جدول دراستك.",
        cta_streak: "ابدأ سلسلتك اليوم",
        cta_title: "مستعد للارتقاء بدراستك؟",
        cta_desc: "انضم إلى آلاف الطلاب الذين غيّروا طريقة دراستهم. مجاني للأبد.",
        cta_button: "إنشاء حساب مجاني",
        cta_xp: "🎁 احصل على +100 XP عند التسجيل",
        footer_copy: "© 2025 Nahda.Edu. مبنية للطلاب، من طرف الطلاب.",
        footer_credit: "تصميم وبناء",
        footer_tagline: "طالب، للطلاب 🎓",
        nav_dashboard: "الرئيسية",
        nav_pomodoro: "بومودورو",
        nav_tasks: "المهام",
        nav_calendar: "التقويم",
        nav_quiz: "اختبار ذكي",
        nav_achievements: "الإنجازات",
        nav_leaderboard: "المتصدرون",
        nav_friends: "الأصدقاء",
        nav_showcase: "معرض الأعمال",
        nav_profile: "الملف الشخصي",
        nav_signout: "تسجيل الخروج",
        sidebar_tagline: "ارتقِ بدراستك",
        sidebar_xp_to_level: "XP للمستوى",
        sidebar_day_streak: "يوم متواصل",
        clock_close: "انقر في أي مكان للإغلاق · اضغط Esc",
        stat_studied_today: "درست اليوم",
        stat_this_week: "هذا الأسبوع",
        stat_pomodoros: "بومودورو",
        stat_sessions_today: "جلسات اليوم",
        stat_tasks_done: "مهام منجزة",
        stat_remaining: "متبقية",
        stat_study_streak: "أيام متواصلة",
        stat_best: "الأفضل",
        stat_days: "أيام",
        dash_weekly_study: "وقت الدراسة الأسبوعي",
        dash_total: "المجموع",
        dash_todays_tasks: "مهام اليوم",
        dash_view_all: "عرض الكل",
        dash_all_done: "أحسنت! لا مهام متبقية.",
        dash_due: "موعد التسليم",
        dash_manage_tasks: "إدارة كل المهام",
        dash_your_progress: "تقدمك",
        dash_level: "المستوى",
        dash_xp_needed: "XP مطلوب",
        dash_to_level: "للمستوى",
        dash_total_xp: "مجموع XP",
        dash_studied: "درست",
        dash_quick_start: "ابدأ الآن",
        dash_start_pomodoro: "ابدأ بومودورو",
        dash_focus_session: "جلسة تركيز",
        dash_add_task: "إضافة مهمة",
        dash_track_work: "تتبع عملك",
        dash_generate_quiz: "إنشاء اختبار",
        dash_from_pdf: "من ملف PDF",
        dash_recent_badges: "آخر الشارات",
        dash_top_subjects: "أبرز المواد",
        dash_study_time: "وقت الدراسة",
        pom_title: "مؤقت بومودورو",
        pom_subtitle: "عمل عميق في فترات مركزة",
        pom_settings: "الإعدادات",
        pom_focus: "التركيز",
        pom_short_break: "استراحة قصيرة",
        pom_long_break: "استراحة طويلة",
        pom_focus_time: "وقت التركيز",
        pom_break_time: "استراحة قصيرة",
        pom_long_break_time: "استراحة طويلة",
        pom_session: "جلسة #",
        pom_no_subject: "بدون مادة",
        pom_working_on: "ماذا تدرس الآن؟",
        pom_todays_progress: "تقدم اليوم",
        pom_sessions: "الجلسات",
        pom_focused: "وقت التركيز",
        pom_xp_earned: "XP مكتسب",
        pom_all_time: "الكل",
        pom_recent_sessions: "الجلسات الأخيرة",
        pom_no_sessions: "لا توجد جلسات بعد. ابدأ جلسة تركيز الآن!",
        pom_focus_session_label: "جلسة تركيز",
        pom_pro_tip: "نصيحة",
        pom_tip_text: "التخطي يسجل فقط الوقت الذي درست فيه فعلاً — كل دقيقة تحسب!",
        pom_settings_title: "إعدادات المؤقت",
        pom_focus_duration: "مدة التركيز",
        pom_short_break_dur: "استراحة قصيرة",
        pom_long_break_dur: "استراحة طويلة",
        pom_sessions_long: "جلسات → استراحة طويلة",
        pom_auto_breaks: "بدء الاستراحات تلقائياً",
        pom_auto_focus: "بدء التركيز تلقائياً",
        pom_changes_note: "التغييرات تسري بعد التطبيق",
        pom_cancel: "إلغاء",
        pom_apply: "تطبيق",
        pom_session_label: "جلسة",
        pom_sessions_label: "جلسات",
        pom_min: "د",
        todos_title: "المهام",
        todos_add: "إضافة مهمة",
        todos_completed: "مكتملة",
        todos_remaining: "متبقية",
        todos_total: "المجموع",
        todos_done: "منجزة",
        todos_pending: "معلقة",
        todos_urgent: "عاجلة",
        todos_new_task: "مهمة جديدة",
        todos_task_title: "عنوان المهمة",
        todos_description: "الوصف (اختياري)",
        todos_priority: "الأولوية",
        todos_subject: "المادة",
        todos_due_date: "تاريخ التسليم",
        todos_none: "لا شيء",
        todos_cancel: "إلغاء",
        todos_add_btn: "إضافة مهمة",
        todos_filter_all: "الكل",
        todos_filter_pending: "معلقة",
        todos_filter_completed: "مكتملة",
        todos_no_tasks: "لا توجد مهام",
        todos_add_first: "أضف مهمتك الأولى للبدء!",
        todos_no_filter: "لا توجد مهام.",
        todos_overdue: "(متأخرة)",
        friends_title: "الأصدقاء",
        friends_subtitle: "ادرسوا معاً، تطوروا معاً",
        friends_find: "ابحث عن طلاب",
        friends_search_ph: "ابحث باسم المستخدم أو الاسم...",
        friends_search_btn: "بحث",
        friends_already: "أصدقاء",
        friends_requested: "تم الإرسال",
        friends_add: "إضافة",
        friends_requests: "طلبات الصداقة",
        friends_accept: "قبول",
        friends_your_friends: "أصدقاؤك",
        friends_no_friends: "لا أصدقاء بعد",
        friends_no_friends_sub: "ابحث عن طلاب أعلاه لإضافتهم",
        friends_xp: "XP",
        friends_streak: "سلسلة",
        friends_studied: "درس",
        lb_title: "المتصدرون",
        lb_subtitle: "تنافس مع زملائك. تصدر القائمة!",
        lb_xp: "⚡ XP",
        lb_streak: "🔥 سلسلة",
        lb_study_time: "⏱ وقت الدراسة",
        lb_you: "أنت",
        lb_days: "أيام",
        lb_studied: "درست",
        lb_level: "المستوى",
        quiz_title: "منشئ الاختبارات بالذكاء الاصطناعي",
        quiz_subtitle: "ارفع ملف PDF واحصل على اختبار شخصي فوري",
        quiz_drop: "أسقط ملف PDF هنا",
        quiz_drop_sub: "أو انقر للتصفح · الحد الأقصى 10MB",
        quiz_remove: "إزالة",
        quiz_quiz_title: "عنوان الاختبار",
        quiz_title_hint: "(اختياري — سيقترح الذكاء الاصطناعي عنواناً)",
        quiz_title_ph: "مثال: الفصل 3: علم الأحياء الخلوي",
        quiz_difficulty: "مستوى الصعوبة",
        quiz_easy: "سهل",
        quiz_medium: "متوسط",
        quiz_hard: "صعب",
        quiz_mixed: "مختلط",
        quiz_num_questions: "عدد الأسئلة",
        quiz_generate: "إنشاء الاختبار",
        quiz_analyzing: "جارٍ تحليل مستندك...",
        quiz_extracting: "استخراج المفاهيم الرئيسية...",
        quiz_crafting: "صياغة أسئلة ذكية...",
        quiz_adding: "إضافة تلميحات وشروحات...",
        quiz_almost: "على وشك الانتهاء...",
        quiz_wait: "يستغرق هذا عادةً 10-20 ثانية",
        quiz_question: "سؤال",
        quiz_of: "من",
        quiz_explanation: "الشرح",
        quiz_get_ai: "احصل على شرح الذكاء الاصطناعي",
        quiz_getting_ai: "جارٍ الحصول على الملاحظات...",
        quiz_ai_tutor: "المعلم الذكي",
        quiz_correct: "صحيح! +XP",
        quiz_incorrect: "خطأ",
        quiz_see_results: "عرض النتائج",
        quiz_next: "السؤال التالي",
        quiz_xp_earned: "XP مكتسب",
        quiz_new_quiz: "اختبار جديد",
        quiz_retry: "إعادة المحاولة",
        quiz_correct_label: "صحيح",
        profile_edit: "تعديل الملف الشخصي",
        profile_save: "حفظ",
        profile_cancel: "إلغاء",
        profile_bio_ph: "نبذة عنك...",
        profile_full_name_ph: "الاسم الكامل",
        profile_level: "المستوى",
        profile_streak: "سلسلة",
        profile_total_xp: "مجموع XP",
        profile_member_since: "عضو منذ",
        profile_days: "أيام",
        profile_pts: "نقطة",
        profile_current_level: "المستوى الحالي",
        profile_xp_week: "XP مكتسب هذا الأسبوع",
        profile_showcase: "معرض الأعمال",
        profile_achievements: "الإنجازات الأخيرة",
        profile_app_dev: "مطور التطبيق",
        profile_earned: "مكتسب",
        showcase_title: "معرض الأعمال",
        showcase_subtitle: "شارك أعمالك الأكاديمية — أوراق بحثية، مشاريع، وأبحاث",
        showcase_add: "إضافة عمل",
        showcase_form_title: "إضافة إلى المعرض",
        showcase_title_ph: "العنوان (مثال: بحث حول تأثير تغير المناخ)",
        showcase_type: "النوع",
        showcase_subject: "المادة / المقرر",
        showcase_subject_ph: "مثال: أحياء، CS101",
        showcase_desc: "الوصف",
        showcase_desc_ph: "وصف مختصر لعملك...",
        showcase_link: "رابط خارجي (اختياري)",
        showcase_link_ph: "https://docs.google.com/...",
        showcase_pdf: "رفع PDF (اختياري، الحد الأقصى 20 MB)",
        showcase_pdf_click: "انقر لرفع ملف PDF",
        showcase_public: "عام — يظهر في ملفك الشخصي",
        showcase_private: "خاص — لك فقط",
        showcase_cancel: "إلغاء",
        showcase_submit: "إضافة إلى المعرض",
        showcase_uploading: "جارٍ رفع PDF…",
        showcase_saving: "جارٍ الحفظ…",
        showcase_no_works: "لا توجد أعمال بعد",
        showcase_no_works_sub: "شارك أعمالك الأكاديمية وأظهرها في ملفك الشخصي.",
        showcase_add_first: "أضف عملك الأول",
        showcase_public_label: "عام",
        showcase_private_label: "خاص",
        showcase_view_link: "عرض الرابط",
        showcase_view_pdf: "عرض PDF",
        showcase_hide_pdf: "إخفاء PDF",
        showcase_open_tab: "فتح في تبويب جديد",
    },

    fr: {
        greeting_morning: "Bonjour",
        greeting_afternoon: "Bon après-midi",
        greeting_evening: "Bonsoir",
        sign_in: "Se connecter",
        get_started: "Commencer gratuitement",
        hero_badge: "Étudie. Gagne des XP. Monte en niveau. Répète.",
        hero_title_1: "Étudie plus intelligemment.",
        hero_title_2: "Monte en niveau.",
        hero_desc: "La seule plateforme de productivité qui rend l'étude addictive.",
        hero_cta: "Commencer gratuitement",
        hero_students: "étudiants déjà en progression",
        stat_pass: "Amélioration du taux de réussite",
        stat_daily: "Étude quotidienne moyenne",
        stat_quizzes: "Quiz IA générés",
        stat_sessions: "Sessions d'étude complétées",
        features_label: "Tout ce dont vous avez besoin",
        features_title: "Conçu pour les étudiants sérieux",
        features_desc: "Chaque fonctionnalité conçue pour vous garder motivé, organisé et en progression.",
        feat_pomodoro_title: "Minuteur Pomodoro",
        feat_pomodoro_desc: "Concentrez-vous en sprints. Suivez chaque session et gagnez des XP.",
        feat_quiz_title: "Générateur de Quiz IA",
        feat_quiz_desc: "Téléchargez n'importe quel PDF et obtenez un quiz personnalisé instantané.",
        feat_gamify_title: "Gamification",
        feat_gamify_desc: "Gagnez des XP, montez de niveau, débloquez des badges.",
        feat_social_title: "Étude sociale",
        feat_social_desc: "Ajoutez des amis, rivalisez dans les classements.",
        feat_tasks_title: "Tâches intelligentes",
        feat_tasks_desc: "Organisez les tâches par matière, priorité et date limite.",
        feat_calendar_title: "Calendrier d'étude",
        feat_calendar_desc: "Planifiez des sessions, suivez les examens.",
        cta_streak: "Commencez votre série aujourd'hui",
        cta_title: "Prêt à améliorer vos études ?",
        cta_desc: "Rejoignez des milliers d'étudiants. Gratuit pour toujours.",
        cta_button: "Créer un compte gratuit",
        cta_xp: "🎁 Obtenez +100 XP rien que pour vous inscrire",
        footer_copy: "© 2025 Nahda.Edu. Construit pour les étudiants, par les étudiants.",
        footer_credit: "Conçu et développé par",
        footer_tagline: "un étudiant, pour les étudiants 🎓",
        nav_dashboard: "Tableau de bord",
        nav_pomodoro: "Pomodoro",
        nav_tasks: "Tâches",
        nav_calendar: "Calendrier",
        nav_quiz: "Quiz IA",
        nav_achievements: "Succès",
        nav_leaderboard: "Classement",
        nav_friends: "Amis",
        nav_showcase: "Vitrine",
        nav_profile: "Profil",
        nav_signout: "Se déconnecter",
        sidebar_tagline: "Progressez dans vos études",
        sidebar_xp_to_level: "XP pour niveau",
        sidebar_day_streak: "jours de suite",
        clock_close: "Cliquez n'importe où pour fermer · Appuyez sur Esc",
        stat_studied_today: "Étudié aujourd'hui",
        stat_this_week: "cette semaine",
        stat_pomodoros: "Pomodoros",
        stat_sessions_today: "sessions aujourd'hui",
        stat_tasks_done: "Tâches faites",
        stat_remaining: "restantes",
        stat_study_streak: "Série d'étude",
        stat_best: "Meilleur",
        stat_days: "jours",
        dash_weekly_study: "Temps d'étude hebdomadaire",
        dash_total: "total",
        dash_todays_tasks: "Tâches du jour",
        dash_view_all: "Voir tout",
        dash_all_done: "Tout est fait ! Ajoutez des tâches.",
        dash_due: "Échéance",
        dash_manage_tasks: "Gérer toutes les tâches",
        dash_your_progress: "Votre progression",
        dash_level: "Niveau",
        dash_xp_needed: "XP nécessaires",
        dash_to_level: "vers niveau",
        dash_total_xp: "XP total",
        dash_studied: "Étudié",
        dash_quick_start: "Démarrage rapide",
        dash_start_pomodoro: "Lancer Pomodoro",
        dash_focus_session: "Session de concentration",
        dash_add_task: "Ajouter une tâche",
        dash_track_work: "Suivre votre travail",
        dash_generate_quiz: "Générer un quiz",
        dash_from_pdf: "Depuis votre PDF",
        dash_recent_badges: "Badges récents",
        dash_top_subjects: "Meilleures matières",
        dash_study_time: "Temps d'étude",
        pom_title: "Minuteur Pomodoro",
        pom_subtitle: "Travail profond en intervalles concentrés",
        pom_settings: "Paramètres",
        pom_focus: "Concentration",
        pom_short_break: "Pause courte",
        pom_long_break: "Pause longue",
        pom_focus_time: "Temps de concentration",
        pom_break_time: "Pause courte",
        pom_long_break_time: "Pause longue",
        pom_session: "Session #",
        pom_no_subject: "Sans matière",
        pom_working_on: "Sur quoi travaillez-vous ?",
        pom_todays_progress: "Progrès du jour",
        pom_sessions: "Sessions",
        pom_focused: "Concentré",
        pom_xp_earned: "XP gagnés",
        pom_all_time: "Total",
        pom_recent_sessions: "Sessions récentes",
        pom_no_sessions: "Aucune session. Démarrez votre première session !",
        pom_focus_session_label: "Session de concentration",
        pom_pro_tip: "Conseil",
        pom_tip_text: "Passer enregistre uniquement le temps réellement étudié — chaque minute compte !",
        pom_settings_title: "Paramètres du minuteur",
        pom_focus_duration: "Durée de concentration",
        pom_short_break_dur: "Pause courte",
        pom_long_break_dur: "Pause longue",
        pom_sessions_long: "Sessions → Pause longue",
        pom_auto_breaks: "Démarrer les pauses automatiquement",
        pom_auto_focus: "Démarrer la concentration automatiquement",
        pom_changes_note: "Les changements prennent effet après application",
        pom_cancel: "Annuler",
        pom_apply: "Appliquer",
        pom_session_label: "session",
        pom_sessions_label: "sessions",
        pom_min: "min",
        todos_title: "Tâches",
        todos_add: "Ajouter une tâche",
        todos_completed: "complétées",
        todos_remaining: "restantes",
        todos_total: "Total",
        todos_done: "Faites",
        todos_pending: "En attente",
        todos_urgent: "Urgent",
        todos_new_task: "Nouvelle tâche",
        todos_task_title: "Titre de la tâche",
        todos_description: "Description (optionnelle)",
        todos_priority: "Priorité",
        todos_subject: "Matière",
        todos_due_date: "Date limite",
        todos_none: "Aucune",
        todos_cancel: "Annuler",
        todos_add_btn: "Ajouter la tâche",
        todos_filter_all: "tout",
        todos_filter_pending: "en attente",
        todos_filter_completed: "complétées",
        todos_no_tasks: "Aucune tâche ici",
        todos_add_first: "Ajoutez votre première tâche pour commencer !",
        todos_no_filter: "Aucune tâche.",
        todos_overdue: "(en retard)",
        friends_title: "Amis",
        friends_subtitle: "Étudiez ensemble, progressez ensemble",
        friends_find: "Trouver des étudiants",
        friends_search_ph: "Rechercher par nom d'utilisateur ou nom...",
        friends_search_btn: "Rechercher",
        friends_already: "Amis",
        friends_requested: "Demande envoyée",
        friends_add: "Ajouter",
        friends_requests: "Demandes d'amis",
        friends_accept: "Accepter",
        friends_your_friends: "Vos amis",
        friends_no_friends: "Pas encore d'amis",
        friends_no_friends_sub: "Recherchez des étudiants ci-dessus pour les ajouter",
        friends_xp: "XP",
        friends_streak: "Série",
        friends_studied: "Étudié",
        lb_title: "Classement",
        lb_subtitle: "Rivalisez avec vos camarades. Montez en tête !",
        lb_xp: "⚡ XP",
        lb_streak: "🔥 Série",
        lb_study_time: "⏱ Temps d'étude",
        lb_you: "Vous",
        lb_days: "jours",
        lb_studied: "étudié",
        lb_level: "Niveau",
        quiz_title: "Générateur de Quiz IA",
        quiz_subtitle: "Téléchargez un PDF et obtenez un quiz personnalisé instantané",
        quiz_drop: "Déposez votre PDF ici",
        quiz_drop_sub: "ou cliquez pour parcourir · max 10 Mo",
        quiz_remove: "Supprimer",
        quiz_quiz_title: "Titre du quiz",
        quiz_title_hint: "(optionnel — l'IA en suggérera un)",
        quiz_title_ph: "ex. Chapitre 3 : Biologie cellulaire",
        quiz_difficulty: "Difficulté",
        quiz_easy: "Facile",
        quiz_medium: "Moyen",
        quiz_hard: "Difficile",
        quiz_mixed: "Mixte",
        quiz_num_questions: "Nombre de questions",
        quiz_generate: "Générer le quiz",
        quiz_analyzing: "Analyse de votre document...",
        quiz_extracting: "Extraction des concepts clés...",
        quiz_crafting: "Création de questions intelligentes...",
        quiz_adding: "Ajout d'indices et d'explications...",
        quiz_almost: "Presque prêt...",
        quiz_wait: "Cela prend généralement 10 à 20 secondes",
        quiz_question: "Question",
        quiz_of: "sur",
        quiz_explanation: "Explication",
        quiz_get_ai: "Obtenir une explication IA",
        quiz_getting_ai: "Obtention des commentaires IA...",
        quiz_ai_tutor: "Tuteur IA",
        quiz_correct: "Correct ! +XP",
        quiz_incorrect: "Incorrect",
        quiz_see_results: "Voir les résultats",
        quiz_next: "Question suivante",
        quiz_xp_earned: "XP gagnés",
        quiz_new_quiz: "Nouveau quiz",
        quiz_retry: "Réessayer",
        quiz_correct_label: "correct",
        profile_edit: "Modifier le profil",
        profile_save: "Enregistrer",
        profile_cancel: "Annuler",
        profile_bio_ph: "Votre biographie...",
        profile_full_name_ph: "Nom complet",
        profile_level: "Niveau",
        profile_streak: "Série",
        profile_total_xp: "XP total",
        profile_member_since: "Membre depuis",
        profile_days: "jours",
        profile_pts: "pts",
        profile_current_level: "Niveau actuel",
        profile_xp_week: "XP gagnés cette semaine",
        profile_showcase: "Vitrine des travaux",
        profile_achievements: "Succès récents",
        profile_app_dev: "Développeur de l'app",
        profile_earned: "Gagné",
        showcase_title: "Vitrine des travaux",
        showcase_subtitle: "Partagez vos travaux académiques — articles, projets et recherches",
        showcase_add: "Ajouter un travail",
        showcase_form_title: "Ajouter à la vitrine",
        showcase_title_ph: "Titre (ex. Recherche sur l'impact climatique)",
        showcase_type: "Type",
        showcase_subject: "Matière / Cours",
        showcase_subject_ph: "ex. Biologie, CS101",
        showcase_desc: "Description",
        showcase_desc_ph: "Brève description de votre travail...",
        showcase_link: "Lien externe (optionnel)",
        showcase_link_ph: "https://docs.google.com/...",
        showcase_pdf: "Télécharger un PDF (optionnel, max 20 Mo)",
        showcase_pdf_click: "Cliquez pour télécharger un PDF",
        showcase_public: "Public — visible sur votre profil",
        showcase_private: "Privé — visible uniquement par vous",
        showcase_cancel: "Annuler",
        showcase_submit: "Ajouter à la vitrine",
        showcase_uploading: "Téléchargement du PDF…",
        showcase_saving: "Enregistrement…",
        showcase_no_works: "Aucun travail encore",
        showcase_no_works_sub: "Partagez vos travaux académiques et faites-les apparaître sur votre profil public.",
        showcase_add_first: "Ajoutez votre premier travail",
        showcase_public_label: "Public",
        showcase_private_label: "Privé",
        showcase_view_link: "Voir le lien",
        showcase_view_pdf: "Voir le PDF",
        showcase_hide_pdf: "Masquer le PDF",
        showcase_open_tab: "Ouvrir dans un nouvel onglet",
    },
};

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: TranslationKey) => string;
    isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>("en");

    useEffect(() => {
        const saved = localStorage.getItem("nahda-lang") as Language;
        if (saved && ["en", "ar", "fr"].includes(saved)) setLanguageState(saved);
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("nahda-lang", lang);
    };

    const t = (key: TranslationKey): string =>
        translations[language][key] ?? translations.en[key] ?? key;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === "ar" }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
    return ctx;
}