"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar" | "fr";

export const translations = {
    en: {
        // Greeting
        greeting_morning: "Good morning",
        greeting_afternoon: "Good afternoon",
        greeting_evening: "Good evening",
        // Landing
        sign_in: "Sign in",
        get_started: "Get started free",
        hero_badge: "Study. Earn XP. Level Up. Repeat.",
        hero_title_1: "Study Smarter.",
        hero_title_2: "Level Up.",
        hero_desc: "The only productivity platform that makes studying addictive. Pomodoro sessions, AI quizzes, real-time leaderboards, and a friends system built for students.",
        hero_cta: "Start for free",
        hero_students: "students already leveling up",
        stat_pass: "Pass rate improvement",
        stat_daily: "Average daily study",
        stat_quizzes: "AI quizzes generated",
        stat_sessions: "Study sessions completed",
        features_label: "Everything you need",
        features_title: "Built for serious students",
        features_desc: "Every feature designed to keep you motivated, organized, and making progress.",
        feat_pomodoro_title: "Pomodoro Timer",
        feat_pomodoro_desc: "Focus in deep work sprints. Track every session and earn XP as you study.",
        feat_quiz_title: "AI Quiz Generator",
        feat_quiz_desc: "Upload any PDF and get an instant personalized quiz. Study smarter with AI.",
        feat_gamify_title: "Gamification",
        feat_gamify_desc: "Earn XP, level up, unlock badges, and maintain study streaks.",
        feat_social_title: "Social Study",
        feat_social_desc: "Add friends, compete on leaderboards, and hold each other accountable.",
        feat_tasks_title: "Smart Tasks",
        feat_tasks_desc: "Organize tasks by subject, priority, and deadline. Never miss a thing.",
        feat_calendar_title: "Study Calendar",
        feat_calendar_desc: "Plan sessions, track exams, and visualize your entire study schedule.",
        cta_streak: "Start your streak today",
        cta_title: "Ready to level up your studies?",
        cta_desc: "Join thousands of students who have transformed how they study. Free forever. No credit card required.",
        cta_button: "Create free account",
        cta_xp: "🎁 Get +100 XP just for signing up",
        footer_copy: "© 2025 Nahda.Edu. Built for students, by students.",
        footer_credit: "Designed & built by",
        footer_tagline: "a student, for students 🎓",
        // Sidebar nav
        nav_dashboard: "Dashboard",
        nav_pomodoro: "Pomodoro",
        nav_tasks: "Tasks",
        nav_calendar: "Calendar",
        nav_quiz: "AI Quiz",
        nav_achievements: "Achievements",
        nav_leaderboard: "Leaderboard",
        nav_friends: "Friends",
        nav_showcase: "Showcase",
        nav_profile: "Profile",
        nav_signout: "Sign out",
        sidebar_tagline: "Level up your studies",
        sidebar_xp_to_level: "XP to level",
        sidebar_day_streak: "day streak",
        clock_close: "Click anywhere to close · Press Esc",
        // Dashboard stats
        stat_studied_today: "Studied Today",
        stat_this_week: "this week",
        stat_pomodoros: "Pomodoros",
        stat_sessions_today: "sessions today",
        stat_tasks_done: "Tasks Done",
        stat_remaining: "remaining",
        stat_study_streak: "Study Streak",
        stat_best: "Best",
        stat_days: "days",
        // Dashboard sections
        dash_weekly_study: "Weekly Study Time",
        dash_total: "total",
        dash_todays_tasks: "Today's Tasks",
        dash_view_all: "View all",
        dash_all_done: "All caught up! Add some tasks.",
        dash_due: "Due",
        dash_manage_tasks: "Manage all tasks",
        dash_your_progress: "Your Progress",
        dash_level: "Level",
        dash_xp_needed: "XP needed",
        dash_to_level: "to Level",
        dash_total_xp: "Total XP",
        dash_studied: "Studied",
        dash_quick_start: "Quick Start",
        dash_start_pomodoro: "Start Pomodoro",
        dash_focus_session: "Focus session",
        dash_add_task: "Add Task",
        dash_track_work: "Track your work",
        dash_generate_quiz: "Generate Quiz",
        dash_from_pdf: "From your PDF",
        dash_recent_badges: "Recent Badges",
        dash_top_subjects: "Top Subjects",
        dash_study_time: "Study time",
    },
    ar: {
        greeting_morning: "صباح الخير",
        greeting_afternoon: "مساء الخير",
        greeting_evening: "مساء الخير",
        sign_in: "تسجيل الدخول",
        get_started: "ابدأ مجاناً",
        hero_badge: "ادرس. اكسب XP. ارتقِ. كرر.",
        hero_title_1: "ادرس بذكاء.",
        hero_title_2: "ارتقِ بمستواك.",
        hero_desc: "المنصة الوحيدة للإنتاجية التي تجعل الدراسة مسلية. جلسات بومودورو، اختبارات بالذكاء الاصطناعي، متصدري النتائج المباشرة، ونظام الأصدقاء المصمم للطلاب.",
        hero_cta: "ابدأ مجاناً",
        hero_students: "طالب يرتقون بمستواهم الآن",
        stat_pass: "تحسن نسبة النجاح",
        stat_daily: "متوسط الدراسة اليومية",
        stat_quizzes: "اختبار بالذكاء الاصطناعي",
        stat_sessions: "جلسة دراسية مكتملة",
        features_label: "كل ما تحتاجه",
        features_title: "مصمم للطلاب الجادين",
        features_desc: "كل ميزة مصممة لإبقائك متحفزاً ومنظماً وتحقيق التقدم.",
        feat_pomodoro_title: "مؤقت بومودورو",
        feat_pomodoro_desc: "ركز في جلسات عمل مكثفة. تتبع كل جلسة واكسب XP أثناء دراستك.",
        feat_quiz_title: "منشئ الاختبارات بالذكاء الاصطناعي",
        feat_quiz_desc: "ارفع أي ملف PDF واحصل على اختبار شخصي فوري.",
        feat_gamify_title: "نظام المكافآت",
        feat_gamify_desc: "اكسب XP، ارتقِ بمستواك، افتح الشارات، وحافظ على سلاسل الدراسة.",
        feat_social_title: "الدراسة الاجتماعية",
        feat_social_desc: "أضف أصدقاء، تنافس على المتصدرين، وتحفزوا معاً.",
        feat_tasks_title: "المهام الذكية",
        feat_tasks_desc: "نظم المهام حسب المادة والأولوية والموعد النهائي.",
        feat_calendar_title: "تقويم الدراسة",
        feat_calendar_desc: "خطط للجلسات، تتبع الامتحانات، وصوّر جدول دراستك بالكامل.",
        cta_streak: "ابدأ سلسلتك اليوم",
        cta_title: "مستعد للارتقاء بدراستك؟",
        cta_desc: "انضم إلى آلاف الطلاب الذين غيّروا طريقة دراستهم. مجاني للأبد.",
        cta_button: "إنشاء حساب مجاني",
        cta_xp: "🎁 احصل على +100 XP عند التسجيل",
        footer_copy: "© 2025 Nahda.Edu. مبنية للطلاب، من طرف الطلاب.",
        footer_credit: "تصميم وبناء",
        footer_tagline: "طالب، للطلاب 🎓",
        nav_dashboard: "الرئيسية",
        nav_pomodoro: "بومودورو",
        nav_tasks: "المهام",
        nav_calendar: "التقويم",
        nav_quiz: "اختبار ذكي",
        nav_achievements: "الإنجازات",
        nav_leaderboard: "المتصدرون",
        nav_friends: "الأصدقاء",
        nav_showcase: "معرض الأعمال",
        nav_profile: "الملف الشخصي",
        nav_signout: "تسجيل الخروج",
        sidebar_tagline: "ارتقِ بدراستك",
        sidebar_xp_to_level: "XP للمستوى",
        sidebar_day_streak: "يوم متواصل",
        clock_close: "انقر في أي مكان للإغلاق · اضغط Esc",
        stat_studied_today: "درست اليوم",
        stat_this_week: "هذا الأسبوع",
        stat_pomodoros: "بومودورو",
        stat_sessions_today: "جلسات اليوم",
        stat_tasks_done: "مهام منجزة",
        stat_remaining: "متبقية",
        stat_study_streak: "أيام متواصلة",
        stat_best: "الأفضل",
        stat_days: "أيام",
        dash_weekly_study: "وقت الدراسة الأسبوعي",
        dash_total: "المجموع",
        dash_todays_tasks: "مهام اليوم",
        dash_view_all: "عرض الكل",
        dash_all_done: "أحسنت! لا مهام متبقية.",
        dash_due: "موعد التسليم",
        dash_manage_tasks: "إدارة كل المهام",
        dash_your_progress: "تقدمك",
        dash_level: "المستوى",
        dash_xp_needed: "XP مطلوب",
        dash_to_level: "للمستوى",
        dash_total_xp: "مجموع XP",
        dash_studied: "درست",
        dash_quick_start: "ابدأ الآن",
        dash_start_pomodoro: "ابدأ بومودورو",
        dash_focus_session: "جلسة تركيز",
        dash_add_task: "إضافة مهمة",
        dash_track_work: "تتبع عملك",
        dash_generate_quiz: "إنشاء اختبار",
        dash_from_pdf: "من ملف PDF",
        dash_recent_badges: "آخر الشارات",
        dash_top_subjects: "أبرز المواد",
        dash_study_time: "وقت الدراسة",
    },
    fr: {
        greeting_morning: "Bonjour",
        greeting_afternoon: "Bon après-midi",
        greeting_evening: "Bonsoir",
        sign_in: "Se connecter",
        get_started: "Commencer gratuitement",
        hero_badge: "Étudie. Gagne des XP. Monte en niveau. Répète.",
        hero_title_1: "Étudie plus intelligemment.",
        hero_title_2: "Monte en niveau.",
        hero_desc: "La seule plateforme de productivité qui rend l'étude addictive. Sessions Pomodoro, quiz IA, classements en temps réel et système d'amis conçu pour les étudiants.",
        hero_cta: "Commencer gratuitement",
        hero_students: "étudiants déjà en progression",
        stat_pass: "Amélioration du taux de réussite",
        stat_daily: "Étude quotidienne moyenne",
        stat_quizzes: "Quiz IA générés",
        stat_sessions: "Sessions d'étude complétées",
        features_label: "Tout ce dont vous avez besoin",
        features_title: "Conçu pour les étudiants sérieux",
        features_desc: "Chaque fonctionnalité conçue pour vous garder motivé, organisé et en progression.",
        feat_pomodoro_title: "Minuteur Pomodoro",
        feat_pomodoro_desc: "Concentrez-vous en sprints de travail intensif. Suivez chaque session et gagnez des XP.",
        feat_quiz_title: "Générateur de Quiz IA",
        feat_quiz_desc: "Téléchargez n'importe quel PDF et obtenez un quiz personnalisé instantané.",
        feat_gamify_title: "Gamification",
        feat_gamify_desc: "Gagnez des XP, montez de niveau, débloquez des badges et maintenez vos séries.",
        feat_social_title: "Étude sociale",
        feat_social_desc: "Ajoutez des amis, rivalisez dans les classements et responsabilisez-vous.",
        feat_tasks_title: "Tâches intelligentes",
        feat_tasks_desc: "Organisez les tâches par matière, priorité et date limite.",
        feat_calendar_title: "Calendrier d'étude",
        feat_calendar_desc: "Planifiez des sessions, suivez les examens et visualisez votre programme.",
        cta_streak: "Commencez votre série aujourd'hui",
        cta_title: "Prêt à améliorer vos études ?",
        cta_desc: "Rejoignez des milliers d'étudiants qui ont transformé leur façon d'étudier. Gratuit pour toujours.",
        cta_button: "Créer un compte gratuit",
        cta_xp: "🎁 Obtenez +100 XP rien que pour vous inscrire",
        footer_copy: "© 2025 Nahda.Edu. Construit pour les étudiants, par les étudiants.",
        footer_credit: "Conçu et développé par",
        footer_tagline: "un étudiant, pour les étudiants 🎓",
        nav_dashboard: "Tableau de bord",
        nav_pomodoro: "Pomodoro",
        nav_tasks: "Tâches",
        nav_calendar: "Calendrier",
        nav_quiz: "Quiz IA",
        nav_achievements: "Succès",
        nav_leaderboard: "Classement",
        nav_friends: "Amis",
        nav_showcase: "Vitrine",
        nav_profile: "Profil",
        nav_signout: "Se déconnecter",
        sidebar_tagline: "Progressez dans vos études",
        sidebar_xp_to_level: "XP pour niveau",
        sidebar_day_streak: "jours de suite",
        clock_close: "Cliquez n'importe où pour fermer · Appuyez sur Esc",
        stat_studied_today: "Étudié aujourd'hui",
        stat_this_week: "cette semaine",
        stat_pomodoros: "Pomodoros",
        stat_sessions_today: "sessions aujourd'hui",
        stat_tasks_done: "Tâches faites",
        stat_remaining: "restantes",
        stat_study_streak: "Série d'étude",
        stat_best: "Meilleur",
        stat_days: "jours",
        dash_weekly_study: "Temps d'étude hebdomadaire",
        dash_total: "total",
        dash_todays_tasks: "Tâches du jour",
        dash_view_all: "Voir tout",
        dash_all_done: "Tout est fait ! Ajoutez des tâches.",
        dash_due: "Échéance",
        dash_manage_tasks: "Gérer toutes les tâches",
        dash_your_progress: "Votre progression",
        dash_level: "Niveau",
        dash_xp_needed: "XP nécessaires",
        dash_to_level: "vers niveau",
        dash_total_xp: "XP total",
        dash_studied: "Étudié",
        dash_quick_start: "Démarrage rapide",
        dash_start_pomodoro: "Lancer Pomodoro",
        dash_focus_session: "Session de concentration",
        dash_add_task: "Ajouter une tâche",
        dash_track_work: "Suivre votre travail",
        dash_generate_quiz: "Générer un quiz",
        dash_from_pdf: "Depuis votre PDF",
        dash_recent_badges: "Badges récents",
        dash_top_subjects: "Meilleures matières",
        dash_study_time: "Temps d'étude",
    },
};

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: TranslationKey) => string;
    isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>("en");

    useEffect(() => {
        const saved = localStorage.getItem("nahda-lang") as Language;
        if (saved && ["en", "ar", "fr"].includes(saved)) {
            setLanguageState(saved);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("nahda-lang", lang);
    };

    const t = (key: TranslationKey): string => {
        return translations[language][key] ?? translations.en[key] ?? key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === "ar" }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
    return ctx;
}